// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/pipedrive-sdk/go"
)

// registerSDKWords installs three native boru words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word. Both
// overloads are all-forward (BarrierAllForward), so args are collected
// from the tokens following the word.
func registerSDKWords(r *eng.Registry, client *sdk.PipedriveSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.PipedriveSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.PipedriveSDK, name string) (sdk.PipedriveEntity, error) {
	switch strings.ToLower(name) {
	case "activity_field":
		return client.ActivityField(nil), nil
	case "activity_type":
		return client.ActivityType(nil), nil
	case "billing":
		return client.Billing(nil), nil
	case "call_log":
		return client.CallLog(nil), nil
	case "channel":
		return client.Channel(nil), nil
	case "currency":
		return client.Currency(nil), nil
	case "deal":
		return client.Deal(nil), nil
	case "deal_field":
		return client.DealField(nil), nil
	case "file":
		return client.File(nil), nil
	case "filter":
		return client.Filter(nil), nil
	case "goal":
		return client.Goal(nil), nil
	case "lead":
		return client.Lead(nil), nil
	case "lead_field":
		return client.LeadField(nil), nil
	case "lead_label":
		return client.LeadLabel(nil), nil
	case "lead_source":
		return client.LeadSource(nil), nil
	case "legacy_team":
		return client.LegacyTeam(nil), nil
	case "mailbox":
		return client.Mailbox(nil), nil
	case "meeting":
		return client.Meeting(nil), nil
	case "note":
		return client.Note(nil), nil
	case "note_field":
		return client.NoteField(nil), nil
	case "oauth":
		return client.Oauth(nil), nil
	case "organization":
		return client.Organization(nil), nil
	case "organization_field":
		return client.OrganizationField(nil), nil
	case "organization_relationship":
		return client.OrganizationRelationship(nil), nil
	case "permission_set":
		return client.PermissionSet(nil), nil
	case "person":
		return client.Person(nil), nil
	case "person_field":
		return client.PersonField(nil), nil
	case "pipeline":
		return client.Pipeline(nil), nil
	case "product":
		return client.Product(nil), nil
	case "product_field":
		return client.ProductField(nil), nil
	case "project":
		return client.Project(nil), nil
	case "project_board":
		return client.ProjectBoard(nil), nil
	case "project_phase":
		return client.ProjectPhase(nil), nil
	case "project_template":
		return client.ProjectTemplate(nil), nil
	case "recent":
		return client.Recent(nil), nil
	case "role":
		return client.Role(nil), nil
	case "stage":
		return client.Stage(nil), nil
	case "task":
		return client.Task(nil), nil
	case "user":
		return client.User(nil), nil
	case "user_connection":
		return client.UserConnection(nil), nil
	case "user_setting":
		return client.UserSetting(nil), nil
	case "webhook":
		return client.Webhook(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
