// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/pipedrive-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"activity_field | activity_type | billing | call_log | channel | currency | deal | deal_field | file | filter | goal | lead | lead_field | lead_label | lead_source | legacy_team | mailbox | meeting | note | note_field | oauth | organization | organization_field | organization_relationship | permission_set | person | person_field | pipeline | product | product_field | project | project_board | project_phase | project_template | recent | role | stage | task | user | user_connection | user_setting | webhook"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.PipedriveSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "pipedrive_list",
		Description: "List records from Pipedrive. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "pipedrive_load",
		Description: "Load a single record from Pipedrive. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.PipedriveSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.PipedriveSDK, name string) (sdk.PipedriveEntity, error) {
	switch strings.ToLower(name) {
	case "activity_field":
		return client.ActivityField(nil), nil
	case "activity_type":
		return client.ActivityType(nil), nil
	case "billing":
		return client.Billing(nil), nil
	case "call_log":
		return client.CallLog(nil), nil
	case "channel":
		return client.Channel(nil), nil
	case "currency":
		return client.Currency(nil), nil
	case "deal":
		return client.Deal(nil), nil
	case "deal_field":
		return client.DealField(nil), nil
	case "file":
		return client.File(nil), nil
	case "filter":
		return client.Filter(nil), nil
	case "goal":
		return client.Goal(nil), nil
	case "lead":
		return client.Lead(nil), nil
	case "lead_field":
		return client.LeadField(nil), nil
	case "lead_label":
		return client.LeadLabel(nil), nil
	case "lead_source":
		return client.LeadSource(nil), nil
	case "legacy_team":
		return client.LegacyTeam(nil), nil
	case "mailbox":
		return client.Mailbox(nil), nil
	case "meeting":
		return client.Meeting(nil), nil
	case "note":
		return client.Note(nil), nil
	case "note_field":
		return client.NoteField(nil), nil
	case "oauth":
		return client.Oauth(nil), nil
	case "organization":
		return client.Organization(nil), nil
	case "organization_field":
		return client.OrganizationField(nil), nil
	case "organization_relationship":
		return client.OrganizationRelationship(nil), nil
	case "permission_set":
		return client.PermissionSet(nil), nil
	case "person":
		return client.Person(nil), nil
	case "person_field":
		return client.PersonField(nil), nil
	case "pipeline":
		return client.Pipeline(nil), nil
	case "product":
		return client.Product(nil), nil
	case "product_field":
		return client.ProductField(nil), nil
	case "project":
		return client.Project(nil), nil
	case "project_board":
		return client.ProjectBoard(nil), nil
	case "project_phase":
		return client.ProjectPhase(nil), nil
	case "project_template":
		return client.ProjectTemplate(nil), nil
	case "recent":
		return client.Recent(nil), nil
	case "role":
		return client.Role(nil), nil
	case "stage":
		return client.Stage(nil), nil
	case "task":
		return client.Task(nil), nil
	case "user":
		return client.User(nil), nil
	case "user_connection":
		return client.UserConnection(nil), nil
	case "user_setting":
		return client.UserSetting(nil), nil
	case "webhook":
		return client.Webhook(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
